import i18n from '@/services/i18n';
import { formatDate } from '@/helpers/date/formatDate';
import queryParam from '@/stores/reportsConfig/constants/queryParam';
import configType from '@/stores/reportsConfig/constants/configType';

const isFirstIndex = (index) => index === 0;

const headers = (type) => [
  {
    text: i18n.global.t('Stop reasons'),
    id: 'comment',
    textKey: 'entityName',
    width: '200px',
    isFixed: isFirstIndex,
    isBold: isFirstIndex,
    isLink: true,
    defaultDirection: 'asc',
    relatedParam: queryParam.COMMENT_ID,
  },
  {
    text: i18n.global.t('Speed loss reasons'),
    id: 'performancecomment',
    textKey: 'entityName',
    width: '200px',
    isFixed: isFirstIndex,
    isBold: isFirstIndex,
    isLink: true,
    defaultDirection: 'asc',
    relatedParam: queryParam.PERFORMANCE_COMMENT_ID,
  },
  {
    textKey: 'operator',
    id: 'operator',
    text: i18n.global.t('Operators'),
    type: 'text',
    defaultDirection: 'asc',
    formatFn: (val) => Array.from(val)?.map?.((operator) => (operator || i18n.global.t('Unknown'))).join(', ') ?? '',
    relatedParam: queryParam.OPERATOR_ID,
  },
  {
    textKey: 'station',
    id: 'station',
    text: i18n.global.t('Stations'),
    type: 'text',
    defaultDirection: 'asc',
    relatedParam: queryParam.STATION_ID,
  },
  {
    textKey: 'location',
    id: 'stoplocation',
    text: i18n.global.t('Machine locations'),
    type: 'text',
    defaultDirection: 'asc',
    relatedParam: queryParam.POSITION_ID,
  },
  {
    textKey: 'product',
    id: 'product',
    text: i18n.global.t('products'),
    type: 'text',
    defaultDirection: 'asc',
    relatedParam: queryParam.PRODUCT_ID,
  },
  {
    textKey: 'shiftTemplate',
    id: 'shifttemplate',
    text: i18n.global.t('Shifts'),
    type: 'text',
    defaultDirection: 'asc',
    relatedParam: queryParam.SHIFT_NAME,
  },
  {
    textKey: 'date',
    id: 'date',
    text: i18n.global.t('date'),
    type: 'text',
    defaultDirection: 'asc',
    formatFn: (val) => formatDate(val, 'long'),
    isHidden: type !== configType.SPEEDLOSS,
  },
  {
    text: i18n.global.t('Time'),
    id: 'starttime',
    textKey: 'tableTimeLabel',
    valueKey: 'xScaleValue',
    type: 'text',
    defaultDirection: 'asc',
    isHidden: type !== configType.DOWNTIME,
  },
  {
    textKey: 'valueLabel',
    valueKey: 'valueSec',
    id: 'stopduration',
    text: i18n.global.t('Duration'),
    align: 'end',
    type: 'number',
    defaultDirection: 'desc',
    isDurationValue: true,
  },
  {
    textKey: 'valueLabel',
    valueKey: 'valueSec',
    id: 'performancelossduration',
    text: i18n.global.t('Duration'),
    align: 'end',
    type: 'number',
    defaultDirection: 'desc',
    isDurationValue: true,
  },
  {
    textKey: 'notes',
    id: 'notes',
    text: i18n.global.t('Notes'),
    type: 'text',
    defaultDirection: 'asc',
    noTruncation: true,
  },
  {
    textKey: 'notes',
    id: 'performancelossnotes',
    text: i18n.global.t('Notes'),
    type: 'text',
    defaultDirection: 'asc',
    noTruncation: true,
  },
];
export default headers;
