import { OFFICE_USER } from '@/constants/userRoles';

export const getShiftViewProductTourConfig = (flowStates) => ({
  isDemoFlow: true,
  description: 'How to optimize your production with Shift View.',
  allowedUserRoles: [OFFICE_USER],
  flows: {
    svWelcome: {
      id: 'svWelcome',
      title: 'Welcome to Evocon 👋',
      isCompleted: flowStates?.svWelcome ?? false,
      steps: [
        {
          title: 'Welcome to Evocon',
          descrLines: ['This self-guided product tour will help you understand the basics of Evocon, how it addresses your production monitoring needs, and the benefits it provides.'],
          img: 'product-tour/sv-welcome/sv-welcome-1.png',
          tertiaryBtnText: 'Close',
        },
        {
          title: 'Checklists to guide you',
          descrLines: [`Click anywhere in the main menu and you'll find a checklist with items to learn about.
              If you'd rather explore on your own, just minimize it and navigate Evocon on your own.`],
          img: 'product-tour/sv-welcome/sv-welcome-2.png',
          showBackBtn: true,
          tertiaryBtnText: 'Close',
        },
        {
          title: 'Demo data',
          descrLines: [`While you tour the system, a small reminder this is a demo environment that aims to reflect the real world.
                If you want to experience Evocon with real data, then starting a free trial is the best way.`],
          img: 'product-tour/sv-welcome/sv-welcome-3.png',
          showBackBtn: true,
          tertiaryBtnText: 'Close',
        },
      ],
    },
    svIntro: {
      id: 'svIntro',
      title: 'How Shift View works?',
      isCompleted: flowStates?.svIntro ?? false,
      steps: [
        {
          title: 'Welcome to Shift View',
          descrLines: [`Shift View represents a single station's (machine or production line) performance for one shift,
                offering an hour-by-hour breakdown and key metrics to assess shift efficiency.`],
          img: 'product-tour/sv-intro/sv-intro-1.png',
          tertiaryBtnText: 'Close',
        },
        {
          title: 'Production timeline',
          descrLines: ['Each horizontal bar shows one hour of production. For example, if the shift runs from 8:00 to 16:00, the first bar displays data from 8:00 to 9:00.',
            'The view updates every minute using data from sensors or other inputs.'],
          img: 'product-tour/sv-intro/sv-intro-2.png',
          showBackBtn: true,
          tertiaryBtnText: 'Close',
        },
        {
          title: 'What are the circles?',
          descrLines: ['Each circle represents 1 minute of production.',
            "If the cycle time of what you are producing is 1 pcs/min, then 1 circle = 1 product (and 60 circles per hour). If it's 5 pcs/min, then 1 circle = 5 products and so on."],
          img: 'product-tour/sv-intro/sv-intro-3.png',
          showBackBtn: true,
          tertiaryBtnText: 'Close',
        },
        {
          title: 'Green = All is good',
          descrLines: ['Green indicates that everything is good - your machine is producing at optimal speed.', 'To continue our example, then 1 pcs every minute.'],
          img: 'product-tour/sv-intro/sv-intro-4.png',
          showBackBtn: true,
          tertiaryBtnText: 'Close',
        },
        {
          title: 'Yellow = Speed loss',
          descrLines: ['These areas indicate the time when you were producing below optimal speed.', 'For example, instead of doing 5 pcs in 5 minutes, you did 4.'],
          img: 'product-tour/sv-intro/sv-intro-5.png',
          showBackBtn: true,
          tertiaryBtnText: 'Close',
        },
        {
          title: 'Red = No bueno',
          descrLines: ['Red areas indicate production stops.', 'For example, if for 3 minutes there are no new signals from the sensor, then the system will show a stop.'],
          img: 'product-tour/sv-intro/sv-intro-6.png',
          showBackBtn: true,
          tertiaryBtnText: 'Close',
        },
        {
          title: 'Gray(s) = Planned stops',
          descrLines: ['And finally there are gray areas that indicate production stops that were planned and were either included (light gray) or excluded (dark gray) from OEE calculation.'],
          img: 'product-tour/sv-intro/sv-intro-7.png',
          showBackBtn: true,
          tertiaryBtnText: 'Close',
        },
        {
          title: 'Visual feedback made simple',
          descrLines: ['Now you know how easy and intuitive it is to track the performance of shifts in Evocon.', 'No more gut feelings, no more guesses.'],
          img: 'product-tour/sv-intro/sv-intro-8.png',
          showBackBtn: true,
          tertiaryBtnText: 'Close',
        },
      ],
    },
    svDtTracking: {
      id: 'svDtTracking',
      title: 'Tracking downtime',
      isCompleted: flowStates?.svDtTracking ?? false,
      steps: [
        {
          title: 'Downtime tracking',
          descrLines: [`Production stops in Evocon are shown as red (no reason), dark red (unplanned reason), light gray (planned reason, included in OEE),
                and dark gray (planned reason, excluded from OEE) providing a clear visual overview of downtime in each shift.`],
          img: 'product-tour/sv-dt-tracking/sv-dt-tracking-1.png',
          tertiaryBtnText: 'Close',
        },
        {
          title: 'How to add stop reasons?',
          descrLines: ['To add reasons to stops, all you need to do is click on a production stop (or double-clicking for faster access) and follow the UI to complete the process.'],
          img: 'product-tour/sv-dt-tracking/sv-dt-tracking-2.png',
          showBackBtn: true,
          tertiaryBtnText: 'Close',
        },
        {
          title: 'Downtime overview',
          descrLines: ['By clicking on Downtime in the footer of Shift View, you can get a full overview of all stops during a shift.'],
          img: 'product-tour/sv-dt-tracking/sv-dt-tracking-3.png',
          showBackBtn: true,
          tertiaryBtnText: 'Close',
        },
        {
          title: 'Downtime alerts',
          descrLines: ["Finally, you can enhance downtime tracking by creating email alerts, so you're instantly notified when specific stop reasons require action."],
          img: 'product-tour/sv-dt-tracking/sv-dt-tracking-4.png',
          showBackBtn: true,
          tertiaryBtnText: 'Close',
        },
      ],
    },
    svMonitoring: {
      id: 'svMonitoring',
      title: 'Monitoring production speed',
      isCompleted: flowStates?.svMonitoring ?? false,
      steps: [
        {
          title: 'Insight into production speed',
          descrLines: [`The speed graph displays production speed data,
            enabling operators to determine whether they are meeting or falling below the established target for the product.`],
          img: 'product-tour/sv-monitoring/sv-monitoring-1.png',
          tertiaryBtnText: 'Close',
        },
        {
          title: 'Actual vs potential',
          descrLines: ['Hourly production totals are shown on the right, highlighting the gap between actual and potential output.'],
          img: 'product-tour/sv-monitoring/sv-monitoring-2.png',
          showBackBtn: true,
          tertiaryBtnText: 'Close',
        },
        {
          title: 'Product changeovers',
          descrLines: ['When you mark a product changeover (by clicking a product circle and changing the product), Evocon recalculates hourly targets based on the new speed target.'],
          img: 'product-tour/sv-monitoring/sv-monitoring-3.png',
          showBackBtn: true,
          tertiaryBtnText: 'Close',
        },
        {
          title: 'Commenting speed loss',
          descrLines: ['To track reasons for speed loss, just click on the yellow areas and add reasons just like you do for downtime.'],
          img: 'product-tour/sv-monitoring/sv-monitoring-4.png',
          showBackBtn: true,
          tertiaryBtnText: 'Close',
        },
      ],
    },
    svRecording: {
      id: 'svRecording',
      title: 'Record quality',
      isCompleted: flowStates?.svRecording ?? false,
      steps: [
        {
          title: 'Record quality',
          descrLines: ['Recording scrapped products is as easy as adding reasons to stops.',
            'You can mark scrap either by clicking on a product circle or using the scrap tab in the footer—scrapped signals appear in orange.'],
          img: 'product-tour/sv-recording/sv-recording-1.png',
          tertiaryBtnText: 'Close',
        },
        {
          title: 'Automatically register scrap',
          descrLines: ["It's also possible to automate scrap registering in Evocon using multiple sensors or PLC outputs. Learn more about this from your Evocon contact person."],
          img: 'product-tour/sv-recording/sv-recording-2.png',
          showBackBtn: true,
          tertiaryBtnText: 'Close',
        },
      ],
    },
    svEngagement: {
      id: 'svEngagement',
      title: 'Engage operators 👷',
      isCompleted: flowStates?.svEngagement ?? false,
      steps: [
        {
          title: 'Drive engagement',
          descrLines: ['Implementing Shift View on the shop floor strengthens operational discipline and boosts engagement.', 'Operators can register for shifts using the menu on the left 👈.'],
          img: 'product-tour/sv-engagement/sv-engagement-1.png',
          tertiaryBtnText: 'Close',
        },
        {
          title: 'Empower operators',
          descrLines: ['By giving operators a tool to track losses, you empower them to report about actual issues in production.',
            'No more finger pointing, guesses and opinions - everything is visualised as it is to everyone.'],
          img: 'product-tour/sv-engagement/sv-engagement-2.png',
          showBackBtn: true,
          tertiaryBtnText: 'Close',
        },
        {
          title: 'Track OEE',
          descrLines: ["Everyone can also track shift OEE and it's relation to target which is especially useful when you implement a bonus system that is based on improving OEE."],
          img: 'product-tour/sv-engagement/sv-engagement-3.png',
          showBackBtn: true,
          tertiaryBtnText: 'Close',
        },
        {
          title: 'Motivated by Mr Evocon',
          descrLines: ['Furthermore, Mr Evocon keeps your shop floor motivated by changing states based on what the current OEE is.',
            'Not only does this improve the understanding of performance but it engages operators to do better.'],
          img: 'product-tour/sv-engagement/sv-engagement-4.png',
          showBackBtn: true,
          tertiaryBtnText: 'Close',
        },
      ],
    },
  },
});
