/* eslint-disable no-magic-numbers */
export const calculatedNotesData = [{
  keyDefaults: {},
  calculationDefaults: {},
  formatDefaults: {},
  inputItemDefaults: {
    comment: '', commentGroupName: '', commentId: '', commentGroupId: '', stopduration: 0, commentColor: '#000000', stopcount: 0, isFake: false,
  },
  formattedObj: {
    entityKey: 'commentId',
    entityId: [988],
    entityName: 'Test',
    stationId: {},
    entityGroupId: 10,
    entityGroupName: 'Mehaanika GLOB',
    entitySubType: '',
    notesCount: 1,
    notes: 'bn',
    location: 'Teadmata',
    positionId: 0,
    product: `Copy of 100tk\\min, kriidiga kvaliteedi markeerimine - toode ei ole kasutuses, 
      Copy of 100tk\\min, kriidiga kvaliteedi markeerimine - toode ei ole kasutuses, Copy of 100tk\\min, kriidiga kvaliteedi marke`,
    productId: {},
    entityCount: 1,
    entityCountLabel: '1',
    shiftTemplate: 'Kerli uus T1',
    operatorId: null,
    operator: {},
    singleOperator: null,
    station: 'Pakendamine 2',
    stationGroupId: {},
    stationGroup: 'Tehas 2',
    includedInOeeStops: null,
    shiftTime: null,
    value: '1970-01-01T01:00:00.000Z',
    valueSec: 3600,
    valueLabel: '1h 00m 00s',
    color: '#3498DB',
    stoppctPlannedTotalTime: null,
    notIncludedInOeeStops: null,
    xScaleValue: '2022-12-06T14:45:00',
    groupingKey: '2022-12-06T14:45:00',
    tooltipXLabel: '14:45 06.12.2022',
    measureLabel: '14:45',
    tableTimeLabel: '06.12 14:45',
    itemGroupingId: {},
    isFake: false,
    avgDuration: 3600,
    avgDurationVal: '1970-01-01T01:00:00.000Z',
    avgDurationFormatted: '1h 00m 00s',
  },
  unformattedObj: {
    entityKey: null,
    entityId: {},
    entityName: {},
    stationId: {},
    entityGroupId: 10,
    entityGroupName: {},
    entitySubType: null,
    notesCount: 1,
    notes: {},
    location: {},
    positionId: 0,
    product: {},
    productId: {},
    entityCount: 1,
    entityCountLabel: 1,
    shiftTemplate: {},
    operatorId: null,
    operator: {},
    singleOperator: null,
    station: {},
    stationGroupId: {},
    stationGroup: {},
    includedInOeeStops: null,
    shiftTime: null,
    value: 3600,
    valueSec: 3600,
    valueLabel: 3600,
    color: {},
    stoppctPlannedTotalTime: null,
    notIncludedInOeeStops: null,
    xScaleValue: '2022-12-06T14:45:00',
    groupingKey: '2022-12-06T14:45:00',
    tooltipXLabel: '2022-12-06T14:45:00',
    measureLabel: '2022-12-06T14:45:00',
    tableTimeLabel: '2022-12-06T14:45:00',
    itemGroupingId: {},
    isFake: false,
    avgDuration: null,
    avgDurationVal: null,
    avgDurationFormatted: null,
  },
  granularity: 'starttime',
  groupBy: ['starttime'],
  dataPctTotal: 0,
  startDate: '2022-12-06',
  endDate: '2022-12-06',
  translations: {},
  formattingOptions: {
    numberFormattingOptions: {
      groupSeparator: ' ',
      decimalSeparator: '.',
      decimalPlaces: 2,
    },
    dateFormat: { long: 'dd.MM.yyyy', short: 'dd.MM' },
    timeFormat: { short: 'HH:mm', long: 'HH:mm:ss', hour: 'HH' },
  },
  idKeyMap: {
    entityId: 'commentId',
    entityGroupId: 'commentgroupId',
    stationId: 'stationId',
    stationGroupId: 'stationgroupId',
    singleOperator: 'singleoperator',
    shiftTemplate: 'shifttemplate',
    productId: 'productId',
    positionId: 'positionId',
    default: 'commentId',
  },
  idKeyNameKeyMap: {
    entityId: 'comment',
    entityGroupId: 'commentGroupName',
    stationId: 'station',
    stationGroupId: 'stationgroup',
    singleOperator: 'singleoperator',
    shiftTemplate: 'shifttemplate',
    productId: 'product',
    positionId: 'stoplocation',
    default: 'comment',
  },
  entityKey: 'commentId',
  entityId: [988],
  entityName: 'Test',
  stationId: {},
  entityGroupId: 10,
  entityGroupName: 'Mehaanika GLOB',
  entitySubType: '',
  notesCount: 1,
  notes: 'bn',
  location: 'Teadmata',
  positionId: 0,
  product: `Copy of 100tk\\min, kriidiga kvaliteedi markeerimine - toode ei ole kasutuses, 
    Copy of 100tk\\min, kriidiga kvaliteedi markeerimine - toode ei ole kasutuses, Copy of 100tk\\min, kriidiga kvaliteedi marke`,
  productId: {},
  entityCount: 1,
  entityCountLabel: '1',
  shiftTemplate: 'Kerli uus T1',
  operatorId: null,
  operator: {},
  singleOperator: null,
  station: 'Pakendamine 2',
  stationGroupId: {},
  stationGroup: 'Tehas 2',
  includedInOeeStops: null,
  shiftTime: null,
  value: '1970-01-01T01:00:00.000Z',
  valueSec: 3600,
  valueLabel: '1h 00m 00s',
  color: '#3498DB',
  stoppctPlannedTotalTime: null,
  notIncludedInOeeStops: null,
  xScaleValue: '2022-12-06T14:45:00',
  groupingKey: '2022-12-06T14:45:00',
  tooltipXLabel: '14:45 06.12.2022',
  measureLabel: '14:45',
  tableTimeLabel: '06.12 14:45',
  itemGroupingId: {},
  isFake: false,
  avgDuration: 3600,
  avgDurationVal: '1970-01-01T01:00:00.000Z',
  avgDurationFormatted: '1h 00m 00s',
  groups: {},
  stackList: [[0, null]],
  stackMax: 0,
  hidden: false,
}, {
  keyDefaults: {},
  calculationDefaults: {},
  formatDefaults: {},
  inputItemDefaults: {
    comment: '', commentGroupName: '', commentId: '', commentGroupId: '', stopduration: 0, commentColor: '#000000', stopcount: 0, isFake: false,
  },
  formattedObj: {
    entityKey: 'commentId',
    entityId: [988],
    entityName: 'Test',
    stationId: {},
    entityGroupId: 10,
    entityGroupName: 'Mehaanika GLOB',
    entitySubType: '',
    notesCount: 1,
    notes: 'bn',
    location: 'Teadmata',
    positionId: 0,
    product: `Copy of 100tk\\min, kriidiga 
      kvaliteedi markeerimine - toode ei ole kasutuses, Copy of 100tk\\min, kriidiga kvaliteedi markeerimine - toode ei ole kasutuses, Copy of 100tk\\min, kriidiga kvaliteedi marke`,
    productId: {},
    entityCount: 1,
    entityCountLabel: '1',
    shiftTemplate: 'Kerli uus T2',
    operatorId: null,
    operator: {},
    singleOperator: null,
    station: 'Pakendamine 2',
    stationGroupId: {},
    stationGroup: 'Tehas 2',
    includedInOeeStops: null,
    shiftTime: null,
    value: '1970-01-01T01:00:00.000Z',
    valueSec: 3600,
    valueLabel: '1h 00m 00s',
    color: '#3498DB',
    stoppctPlannedTotalTime: null,
    notIncludedInOeeStops: null,
    xScaleValue: '2022-12-06T15:45:00',
    groupingKey: '2022-12-06T15:45:00',
    tooltipXLabel: '15:45 06.12.2022',
    measureLabel: '15:45',
    tableTimeLabel: '06.12 15:45',
    itemGroupingId: {},
    isFake: false,
    avgDuration: 3600,
    avgDurationVal: '1970-01-01T01:00:00.000Z',
    avgDurationFormatted: '1h 00m 00s',
  },
  unformattedObj: {
    entityKey: null,
    entityId: {},
    entityName: {},
    stationId: {},
    entityGroupId: 10,
    entityGroupName: {},
    entitySubType: null,
    notesCount: 1,
    notes: {},
    location: {},
    positionId: 0,
    product: {},
    productId: {},
    entityCount: 1,
    entityCountLabel: 1,
    shiftTemplate: {},
    operatorId: null,
    operator: {},
    singleOperator: null,
    station: {},
    stationGroupId: {},
    stationGroup: {},
    includedInOeeStops: null,
    shiftTime: null,
    value: 3600,
    valueSec: 3600,
    valueLabel: 3600,
    color: {},
    stoppctPlannedTotalTime: null,
    notIncludedInOeeStops: null,
    xScaleValue: '2022-12-06T15:45:00',
    groupingKey: '2022-12-06T15:45:00',
    tooltipXLabel: '2022-12-06T15:45:00',
    measureLabel: '2022-12-06T15:45:00',
    tableTimeLabel: '2022-12-06T15:45:00',
    itemGroupingId: {},
    isFake: false,
    avgDuration: null,
    avgDurationVal: null,
    avgDurationFormatted: null,
  },
  granularity: 'starttime',
  groupBy: ['starttime'],
  dataPctTotal: 0,
  startDate: '2022-12-06',
  endDate: '2022-12-06',
  translations: {},
  formattingOptions: {
    numberFormattingOptions: { groupSeparator: ' ', decimalSeparator: '.', decimalPlaces: 2 },
    dateFormat: { long: 'dd.MM.yyyy', short: 'dd.MM' },
    timeFormat: { short: 'HH:mm', long: 'HH:mm:ss', hour: 'HH' },
  },
  idKeyMap: {
    entityId: 'commentId',
    entityGroupId: 'commentgroupId',
    stationId: 'stationId',
    stationGroupId: 'stationgroupId',
    singleOperator: 'singleoperator',
    shiftTemplate: 'shifttemplate',
    productId: 'productId',
    positionId: 'positionId',
    default: 'commentId',
  },
  idKeyNameKeyMap: {
    entityId: 'comment',
    entityGroupId: 'commentGroupName',
    stationId: 'station',
    stationGroupId: 'stationgroup',
    singleOperator: 'singleoperator',
    shiftTemplate: 'shifttemplate',
    productId: 'product',
    positionId: 'stoplocation',
    default: 'comment',
  },
  entityKey: 'commentId',
  entityId: [988],
  entityName: 'Test',
  stationId: {},
  entityGroupId: 10,
  entityGroupName: 'Mehaanika GLOB',
  entitySubType: '',
  notesCount: 1,
  notes: 'bn',
  location: 'Teadmata',
  positionId: 0,
  product: `Copy of 100tk\\min, kriidiga kvaliteedi markeerimine - toode ei ole kasutuses, Copy of 100tk\\min, 
    kriidiga kvaliteedi markeerimine - toode ei ole kasutuses, Copy of 100tk\\min, kriidiga kvaliteedi marke`,
  productId: {},
  entityCount: 1,
  entityCountLabel: '1',
  shiftTemplate: 'Kerli uus T2',
  operatorId: null,
  operator: {},
  singleOperator: null,
  station: 'Pakendamine 2',
  stationGroupId: {},
  stationGroup: 'Tehas 2',
  includedInOeeStops: null,
  shiftTime: null,
  value: '1970-01-01T01:00:00.000Z',
  valueSec: 3600,
  valueLabel: '1h 00m 00s',
  color: '#3498DB',
  stoppctPlannedTotalTime: null,
  notIncludedInOeeStops: null,
  xScaleValue: '2022-12-06T15:45:00',
  groupingKey: '2022-12-06T15:45:00',
  tooltipXLabel: '15:45 06.12.2022',
  measureLabel: '15:45',
  tableTimeLabel: '06.12 15:45',
  itemGroupingId: {},
  isFake: false,
  avgDuration: 3600,
  avgDurationVal: '1970-01-01T01:00:00.000Z',
  avgDurationFormatted: '1h 00m 00s',
  groups: {},
  stackList: [[0, null]],
  stackMax: 0,
  hidden: false,
}];
export default {
  calculatedNotesData,
};
