import {
  DOWNTIME, SPEEDLOSS, SCRAPREASON, OEE, QUANTITY, TIME_USAGE, CHECKLIST,
} from './configType';
import {
  ENTITY_COMMENT, ENTITY_PERF_COMMENT, ENTITY_SCRAP, ENTITY_OEE, ENTITY_QUANTITY, ENTITY_TIME_USAGE, ENTITY_CHECKLIST,
} from './entityType';

export default new Map([
  [DOWNTIME, ENTITY_COMMENT],
  [SPEEDLOSS, ENTITY_PERF_COMMENT],
  [SCRAPREASON, ENTITY_SCRAP],
  [OEE, ENTITY_OEE],
  [QUANTITY, ENTITY_QUANTITY],
  [TIME_USAGE, ENTITY_TIME_USAGE],
  [CHECKLIST, ENTITY_CHECKLIST],
]);
