// @ts-check
/** @typedef {string} DimensionType */
/** @enum {DimensionType} */
export default {
  FACTORY: 'factory',
  STATION: 'station',
  STATION_GROUP: 'stationgroup',
  SHIFT_TEMPLATE: 'shifttemplate',
  COMMENT: 'comment',
  COMMENT_GROUP: 'commentgroup',
  STOP_LOCATION: 'stoplocation',
  PERFORMANCE_COMMENT: 'performancecomment',
  PERFORMANCE_COMMENT_GROUP: 'performancelossgroup',
  PERFORMANCE_LOSS_LOCATION: 'performancelosslocation',
  SCRAP_REASON: 'scrapreason',
  SCRAP_REASON_GROUP: 'scrapreasongroup',
  SHIFT_TIME: 'shifttime',
  PRODUCT: 'product',
  PRODUCT_GROUP: 'productgroup',
  LOT_CODE: 'lotcode',
  PRODUCTION_ORDER: 'productionorder',
  OPERATOR: 'operator',
  TIMELINE_ID: 'timelineid',
  PERFORMANCE_LOSS_INSTANCE_ID: 'performancelossinstanceid',
  SINGLE_OPERATOR: 'singleoperator',
  STARTTIME: 'starttime',
  CHECKLIST: 'checklist',
  CHECKLIST_GROUP: 'checklistgroup',
  CHECKLIST_PIN: 'checklistpin',
  CHECKLIST_DONE_BY: 'doneby',
  PRODUCTION_SPEED_RANGE: 'binrange',
};
