// @ts-check
/** @typedef {string} QueryParamType */
/** @enum {QueryParamType} */
export default {
  ORDER_BY: 'orderBy',
  ORDER_DIR: 'orderDir',
  GRANULARITY: 'granularity',
  PERIOD: 'period',
  BOOKMARK_ID: 'bookmarkId',
  TYPE: 'type',
  NAME: 'name',
  DESCRIPTION: 'description',
  CHART_TYPE: 'chartType',
  CHART_CURVE: 'chartCurve',
  GROUP_BY: 'groupBy',
  FACTORY_ID: 'factoryId',
  STATION_ID: 'stationId',
  STATION_GROUP_ID: 'stationGroupId',
  SHIFT_TEMPLATE: 'shiftTemplate',
  COMMENT_ID: 'commentId',
  COMMENT_GROUP_ID: 'commentGroupId',
  PERFORMANCE_COMMENT_ID: 'performanceCommentId',
  PERFORMANCE_COMMENT_GROUP_ID: 'performanceCommentGroupId',
  PRODUCT_ID: 'productId',
  PRODUCT_GROUP_ID: 'productGroupId',
  LOT_CODE: 'lotCode',
  PRODUCTION_ORDER: 'productionOrder',
  CHECKLIST_ID: 'checklistId',
  CHECKLIST_GROUP_ID: 'checklistGroupId',
  CHECKLIST_STATUS: 'status',
  SHIFT_NAME: 'shiftName',
  OPERATOR_ID: 'operatorId',
  POSITION_ID: 'positionId',
  PERFORMANCE_POSITION_ID: 'performancePositionId',
  STOP_TYPE: 'stopType',
  INVERTED_FILTERS: 'invertedFilters',
  ITEMS_PER_PAGE: 'itemsPerPage',
  PAGE: 'page',
  Y_AXIS: 'yAxis',
  Y_AXIS_RIGHT: 'yAxisRight',
  SCRAP_ID: 'scrapReasonId',
  SCRAP_GROUP_ID: 'scrapReasonGroupId',
  VISIBLE_COLUMNS: 'visibleColumns',
  CHART_LEGEND_STATE: 'chartLegendState',
  CHECKLIST_DONE_BY_ENTITY_ID: 'doneByEntityId',
};
