import { getLongDateTimeField, dtFieldType } from '@/helpers/time/dateTimeFieldLabel';
import { firstUpper } from '@/helpers/string-formatting';
import getHelperFunctions from '@/stores/reportsConfig/configurations/tableColumns/columnHelperFunctions';
import granularity from '@/stores/reportsConfig/constants/granularity';
import i18n from '@/services/i18n';

export default function getCommonTimeColumns(options) {
  const { isLink, isFirstIndex, getPrependImg } = getHelperFunctions(options);
  return [
    {
      text: firstUpper(getLongDateTimeField(dtFieldType.year, options.language)),
      id: granularity.YEAR,
      textKey: 'tableTimeLabel',
      valueKey: 'xScaleValue',
      type: 'text',
      isFixed: isFirstIndex,
      isBold: isFirstIndex,
      isLink,
      defaultDirection: 'asc',
      prependImage: getPrependImg(granularity.YEAR),
      width: '90px',
    },
    {
      text: firstUpper(getLongDateTimeField(dtFieldType.quarter, options.language)),
      id: granularity.QUARTER,
      textKey: 'tableTimeLabel',
      valueKey: 'xScaleValue',
      type: 'text',
      isFixed: isFirstIndex,
      isBold: isFirstIndex,
      isLink,
      defaultDirection: 'asc',
      prependImage: getPrependImg(granularity.QUARTER),
      width: '90px',
    },
    {
      text: firstUpper(getLongDateTimeField(dtFieldType.weekofyear, options.language)),
      id: granularity.WEEKOFYEAR,
      textKey: 'tableTimeLabel',
      valueKey: 'xScaleValue',
      type: 'text',
      isFixed: isFirstIndex,
      isBold: isFirstIndex,
      isLink,
      defaultDirection: 'asc',
      prependImage: getPrependImg(granularity.WEEKOFYEAR),
      width: '100px',
    },
    {
      text: firstUpper(getLongDateTimeField(dtFieldType.month, options.language)),
      id: granularity.MONTH,
      textKey: 'tableTimeLabel',
      valueKey: 'xScaleValue',
      type: 'text',
      isFixed: isFirstIndex,
      isBold: isFirstIndex,
      isLink,
      defaultDirection: 'asc',
      formatFn: (val) => i18n.global.t(val),
      prependImage: getPrependImg(granularity.MONTH),
      width: '100px',
    },
    {
      text: firstUpper(getLongDateTimeField(dtFieldType.weekday, options.language)),
      id: granularity.DAYOFWEEK,
      textKey: 'tableTimeLabel',
      valueKey: 'xScaleValue',
      type: 'text',
      isFixed: isFirstIndex,
      isBold: isFirstIndex,
      isLink,
      defaultDirection: 'asc',
      prependImage: getPrependImg(granularity.DAYOFWEEK),
      width: '100px',
    },
    {
      text: i18n.global.t('date'),
      id: granularity.DATE,
      textKey: 'tableTimeLabel',
      valueKey: 'xScaleValue',
      type: 'text',
      isFixed: isFirstIndex,
      isBold: isFirstIndex,
      isLink,
      defaultDirection: 'asc',
      prependImage: getPrependImg(granularity.DATE),
      width: '120px',
    },
    {
      text: i18n.global.t('Time'),
      id: granularity.STARTTIME,
      textKey: 'tableTimeLabel',
      valueKey: 'xScaleValue',
      type: 'text',
      isFixed: isFirstIndex,
      isBold: isFirstIndex,
      isLink,
      defaultDirection: 'asc',
      prependImage: getPrependImg(granularity.STARTTIME),
      width: '120px',
    },
    {
      text: i18n.global.t('Due time'),
      id: granularity.DUE_TIME,
      textKey: 'tableTimeLabel',
      valueKey: 'xScaleValue',
      type: 'text',
      isFixed: isFirstIndex,
      isBold: isFirstIndex,
      isLink,
      defaultDirection: 'asc',
      prependImage: getPrependImg(granularity.DUE_TIME),
      width: '120px',
    },
  ];
}
