import i18n from '@/services/i18n';
import measure from '@/stores/reportsConfig/constants/measure';
import dimension from '@/stores/reportsConfig/constants/dimension';
import calcMeasure from '@/stores/reportsConfig/constants/calcMeasure';
import queryParam from '@/stores/reportsConfig/constants/queryParam';
import { formatNumber } from '@/helpers/numbers/formatNumber';
import getHelperFunctions from '@/stores/reportsConfig/configurations/tableColumns/columnHelperFunctions';
import formatDuration from '@/helpers/time/formatDuration';
import yAxisKey from '@/stores/reportsConfig/constants/yAxisKey';
import xAxisKey from '@/stores/reportsConfig/constants/xAxisKey';
import { PRODUCTION_SPEED } from '@/stores/reportsConfig/constants/configType';

const singularReportTypes = new Set([PRODUCTION_SPEED]);

export default function getCommonColumns(options) {
  const isSingular = singularReportTypes.has(options.configType);
  const {
    isLink, isFirstIndex, getPrependImg, hasNotesCount, getPlannedTimeAppendText,
  } = getHelperFunctions(options);
  return {
    FACTORY: {
      textKey: 'factory',
      secondaryId: xAxisKey.FACTORY_ID,
      id: dimension.FACTORY,
      text: isSingular ? i18n.global.t('Factory') : i18n.global.t('Factories'),
      type: 'text',
      defaultDirection: 'asc',
      isFixed: isFirstIndex,
      isBold: isFirstIndex,
      isLink,
      relatedParam: queryParam.FACTORY_ID,
      prependImage: getPrependImg(xAxisKey.FACTORY_ID),
      width: '200px',
    },
    STATION: {
      textKey: 'station',
      secondaryId: xAxisKey.STATION_ID,
      id: dimension.STATION,
      text: isSingular ? i18n.global.t('station') : i18n.global.t('Stations'),
      type: 'text',
      defaultDirection: 'asc',
      isFixed: isFirstIndex,
      isBold: isFirstIndex,
      isLink,
      relatedParam: queryParam.STATION_ID,
      prependImage: getPrependImg(xAxisKey.STATION_ID),
      width: '200px',
    },
    STATION_GROUP: {
      textKey: 'stationGroup',
      secondaryId: xAxisKey.STATION_GROUP_ID,
      id: dimension.STATION_GROUP,
      text: isSingular ? i18n.global.t('Station group') : i18n.global.t('Station groups'),
      type: 'text',
      defaultDirection: 'asc',
      isFixed: isFirstIndex,
      isBold: isFirstIndex,
      isLink,
      relatedParam: queryParam.STATION_GROUP_ID,
      prependImage: getPrependImg(xAxisKey.STATION_GROUP_ID),
      width: '200px',
    },
    SINGLE_OPERATOR: {
      textKey: 'singleOperator',
      secondaryId: xAxisKey.SINGLE_OPERATOR,
      id: dimension.SINGLE_OPERATOR,
      text: i18n.global.t('operator'),
      type: 'text',
      defaultDirection: 'asc',
      formatFn: (val) => (val === 'default' ? i18n.global.t('default') : val),
      isFixed: isFirstIndex,
      isBold: isFirstIndex,
      isLink,
      relatedParam: queryParam.OPERATOR_ID,
      prependImage: getPrependImg(xAxisKey.SINGLE_OPERATOR),
      width: '200px',
    },
    PRODUCT: {
      textKey: 'product',
      id: dimension.PRODUCT,
      text: isSingular ? i18n.global.t('Product') : i18n.global.t('products'),
      secondaryId: xAxisKey.PRODUCT_ID,
      type: 'text',
      defaultDirection: 'asc',
      isFixed: isFirstIndex,
      isBold: isFirstIndex,
      isLink,
      prependImage: getPrependImg(xAxisKey.PRODUCT_ID),
      width: '200px',
    },
    PRODUCT_GROUP: {
      textKey: 'productGroup',
      id: dimension.PRODUCT_GROUP,
      text: isSingular ? i18n.global.t('Product group') : i18n.global.t('Product groups'),
      secondaryId: xAxisKey.PRODUCT_GROUP_ID,
      type: 'text',
      defaultDirection: 'asc',
      isFixed: isFirstIndex,
      isBold: isFirstIndex,
      isLink,
      prependImage: getPrependImg(xAxisKey.PRODUCT_GROUP_ID),
      width: '200px',
    },
    SKU: {
      textKey: 'skuLabel',
      id: xAxisKey.SKU,
      secondaryId: xAxisKey.SKU,
      text: i18n.global.t('Product code'),
      type: 'text',
      defaultDirection: 'asc',
      isFixed: isFirstIndex,
      isBold: isFirstIndex,
      isLink,
      prependImage: getPrependImg(xAxisKey.SKU),
      width: '200px',
    },
    LOT_CODE: {
      textKey: 'lotCode',
      id: dimension.LOT_CODE,
      secondaryId: xAxisKey.LOT_CODE,
      text: i18n.global.t('LOT/Batch'),
      type: 'text',
      defaultDirection: 'asc',
      isFixed: isFirstIndex,
      isBold: isFirstIndex,
      isLink,
      relatedParam: queryParam.LOT_CODE,
      prependImage: getPrependImg(xAxisKey.LOT_CODE),
      width: '200px',
    },
    PRODUCTION_ORDER: {
      textKey: 'productionOrder',
      id: dimension.PRODUCTION_ORDER,
      secondaryId: xAxisKey.PRODUCTION_ORDER,
      text: i18n.global.t('Orders'),
      type: 'text',
      defaultDirection: 'asc',
      isFixed: isFirstIndex,
      isBold: isFirstIndex,
      isLink,
      relatedParam: queryParam.PRODUCTION_ORDER,
      prependImage: getPrependImg(xAxisKey.PRODUCTION_ORDER),
      width: '200px',
    },
    SHIFT_TEMPLATE: {
      textKey: 'shiftTemplateLabel',
      id: dimension.SHIFT_TEMPLATE,
      secondaryId: xAxisKey.SHIFT_TEMPLATE,
      text: i18n.global.t('Shifts'),
      type: 'text',
      defaultDirection: 'asc',
      isFixed: isFirstIndex,
      isBold: isFirstIndex,
      isLink,
      prependImage: getPrependImg(xAxisKey.SHIFT_TEMPLATE),
      width: '200px',
    },
    OPERATOR: {
      textKey: 'operator',
      id: dimension.OPERATOR,
      text: i18n.global.t('Operators'),
      type: 'text',
      defaultDirection: 'asc',
      formatFn: (val) => {
        if (!val) return '';
        return Array.from(val).map((operator) => (operator || i18n.global.t('Unknown'))).join(', ');
      },
      relatedParam: queryParam.OPERATOR_ID,
      prependImage: getPrependImg(xAxisKey.OPERATOR),
      width: '200px',
    },
    NOTES_COUNT: {
      textKey: 'notesCount',
      id: measure.NOTES_COUNT,
      text: i18n.global.t('Notes'),
      hasTotal: true,
      type: 'number',
      defaultDirection: 'desc',
      isPopUp: hasNotesCount,
      formatFn: formatNumber,
      prependImage: getPrependImg(yAxisKey.NOTES_COUNT),
      width: '75px',
    },
    NOTES: {
      textKey: 'notes',
      id: measure.NOTES,
      text: i18n.global.t('Notes'),
      type: 'text',
      defaultDirection: 'asc',
      prependImage: getPrependImg(yAxisKey.NOTES_COUNT),
      width: '75px',
    },
    AVG_DURATION: {
      textKey: 'avgDuration',
      valueKey: 'avgDuration',
      id: calcMeasure.AVG_DURATION,
      text: i18n.global.t('Average duration'),
      hasTotal: true,
      type: 'number',
      defaultDirection: 'desc',
      isDurationValue: true,
      formatFn: (val) => formatDuration(val, options.durFormatType, { keepDecimalPlaces: true }),
      prependImage: getPrependImg(yAxisKey.AVG_DURATION_VAL),
      width: '150px',
    },
    AVG_TIME: {
      textKey: 'avgTime',
      valueKey: 'avgTime',
      id: calcMeasure.AVG_TIME,
      text: i18n.global.t('Average time'),
      hasTotal: true,
      type: 'number',
      defaultDirection: 'desc',
      isDurationValue: true,
      formatFn: (val) => formatDuration(val, options.durFormatType, { keepDecimalPlaces: true }),
      prependImage: getPrependImg(yAxisKey.AVG_TIME_VAL),
      width: '150px',
    },
    TOTAL_PLANNED_TIME: {
      textKey: 'totalPlannedTime',
      valueKey: 'totalPlannedTime',
      id: measure.TOTAL_PLANNED_TIME,
      text: i18n.global.t('plannedTime'),
      appendText: ` (${i18n.global.t('Total')})`,
      hasTotal: true,
      type: 'number',
      defaultDirection: 'desc',
      isDurationValue: true,
      formatFn: (val) => formatDuration(val, options.durFormatType, { keepDecimalPlaces: true }),
      width: '150px',
    },
    ENTITY_PCT_PLANNED_TIME: {
      textKey: 'entityPctPlannedTimeLabel',
      valueKey: 'entityPctPlannedTime',
      id: calcMeasure.ENTITY_PCT_PLANNED_TIME,
      text: i18n.global.t('% of planned time'),
      type: 'number',
      defaultDirection: 'desc',
      width: '170px',
      hasTotal: true,
    },
    ROW_PLANNED_TIME: {
      textKey: 'rowPlannedTime',
      valueKey: 'rowPlannedTime',
      id: measure.ROW_PLANNED_TIME,
      text: i18n.global.t('plannedTime'),
      appendText: ` ${getPlannedTimeAppendText()}`,
      hasTotal: true,
      type: 'number',
      defaultDirection: 'desc',
      isDurationValue: true,
      formatFn: (val) => formatDuration(val, options.durFormatType, { keepDecimalPlaces: true }),
      width: '150px',
    },

    OPERATING_TIME: {
      textKey: 'operatingTime',
      secondaryTextKey: 'operatingTimePctFormatted',
      secondaryTextTooltip: `${i18n.global.t('plannedTime')} / ${i18n.global.t('Shift time')}`,
      valueKey: 'operatingTime',
      id: calcMeasure.OPERATING_TIME,
      text: i18n.global.t('Operating time'),
      type: 'number',
      defaultDirection: 'desc',
      hasTotal: true,
      isDurationValue: true,
      formatFn: (val) => formatDuration(val, options.durFormatType, { keepDecimalPlaces: true }),
      width: '150px',
    },
    PLANNED_TIME: {
      textKey: 'plannedTime',
      valueKey: 'plannedTime',
      id: measure.PLANNED_TIME,
      text: i18n.global.t('plannedTime'),
      type: 'number',
      defaultDirection: 'desc',
      hasTotal: true,
      isDurationValue: true,
      formatFn: (val) => formatDuration(val, options.durFormatType, { keepDecimalPlaces: true }),
      width: '150px',
    },
    CALENDAR_TIME: {
      textKey: 'calendarTime',
      valueKey: 'calendarTime',
      id: calcMeasure.CALENDAR_TIME,
      text: i18n.global.t('All time'),
      type: 'number',
      defaultDirection: 'desc',
      hasTotal: false,
      isDurationValue: true,
      formatFn: (val) => formatDuration(val, options.durFormatType, { keepDecimalPlaces: true }),
      width: '150px',
    },
    SHIFT_TIME: {
      textKey: 'shiftTime',
      valueKey: 'shiftTime',
      id: calcMeasure.SHIFT_TIME,
      text: i18n.global.t('Shift time'),
      type: 'number',
      defaultDirection: 'desc',
      hasTotal: true,
      isDurationValue: true,
      formatFn: (val) => formatDuration(val, options.durFormatType, { keepDecimalPlaces: true }),
      width: '150px',
    },
    ROW_PRODUCED_QTY: {
      textKey: 'rowProducedQtyFormatted',
      valueKey: 'rowProducedQty',
      id: measure.ROW_PRODUCED_QTY,
      text: `${i18n.global.t('Total quantity')} (${i18n.global.t('Primary unit').toLowerCase()})`,
      type: 'number',
      defaultDirection: 'desc',
      hasTotal: true,
      width: '120px',
    },
    ROW_PRODUCED_ALT_QTY: {
      textKey: 'rowProducedAltQtyFormatted',
      valueKey: 'rowProducedAltQty',
      id: measure.ROW_PRODUCED_ALT_QTY,
      text: `${i18n.global.t('Total quantity')} (${i18n.global.t('Alternative unit').toLowerCase()})`,
      type: 'number',
      defaultDirection: 'desc',
      hasTotal: true,
      width: '120px',
    },
  };
}
