import i18n from '@/services/i18n';
import measure from '@/stores/reportsConfig/constants/measure';
import calcMeasure from '@/stores/reportsConfig/constants/calcMeasure';

export default function getQuantityColumns() {
  return {
    GOOD_QTY: {
      textKey: 'goodQtyFormatted',
      secondaryTextKey: 'goodQtyPctFormatted',
      valueKey: 'goodQty',
      id: measure.GOOD_QTY,
      text: `${i18n.global.t('Good quantity')} (${i18n.global.t('Primary unit').toLowerCase()})`,
      type: 'number',
      defaultDirection: 'desc',
      hasTotal: true,
      width: '120px',
    },
    GOOD_ALT_QTY: {
      textKey: 'goodAltQtyFormatted',
      valueKey: 'goodAltQty',
      id: measure.GOOD_ALT_QTY,
      text: `${i18n.global.t('Good quantity')} (${i18n.global.t('Alternative unit').toLowerCase()})`,
      type: 'number',
      defaultDirection: 'desc',
      hasTotal: true,
      width: '120px',
    },
    SCRAP_QTY: {
      textKey: 'scrapQtyFormatted',
      secondaryTextKey: 'scrapQtyPctFormatted',
      valueKey: 'scrapQty',
      id: measure.SCRAP_QTY,
      text: `${i18n.global.t('Scrap')} (${i18n.global.t('Primary unit').toLowerCase()})`,
      type: 'number',
      defaultDirection: 'desc',
      hasTotal: true,
      width: '120px',
    },
    SCRAP_ALT_QTY: {
      textKey: 'scrapAltQtyFormatted',
      valueKey: 'scrapAltQty',
      id: measure.SCRAP_ALT_QTY,
      text: `${i18n.global.t('Scrap')} (${i18n.global.t('Alternative unit').toLowerCase()})`,
      type: 'number',
      defaultDirection: 'desc',
      hasTotal: true,
      width: '120px',
    },
    ROW_PRODUCED_QTY: {
      textKey: 'rowProducedQtyFormatted',
      valueKey: 'rowProducedQty',
      id: measure.ROW_PRODUCED_QTY,
      text: `${i18n.global.t('Total quantity')} (${i18n.global.t('Primary unit').toLowerCase()})`,
      type: 'number',
      defaultDirection: 'desc',
      hasTotal: true,
      width: '120px',
    },
    POTENTIAL_QTY: {
      textKey: 'potentialQtyFormatted',
      valueKey: 'potentialQty',
      id: calcMeasure.POTENTIAL_QTY,
      text: `${i18n.global.t('Potential')} (${i18n.global.t('Primary unit').toLowerCase()})`,
      type: 'number',
      defaultDirection: 'desc',
      hasTotal: true,
      width: '120px',
    },
    POTENTIAL_ALT_QTY: {
      textKey: 'potentialAltQtyFormatted',
      valueKey: 'potentialAltQty',
      id: calcMeasure.POTENTIAL_ALT_QTY,
      text: `${i18n.global.t('Potential')} (${i18n.global.t('Alternative unit').toLowerCase()})`,
      type: 'number',
      defaultDirection: 'desc',
      hasTotal: true,
      width: '120px',
    },
    IDEAL_QTY: {
      textKey: 'idealQtyFormatted',
      valueKey: 'idealQty',
      id: measure.IDEAL_QTY,
      text: `${i18n.global.t('idealqty')} (${i18n.global.t('Primary unit').toLowerCase()})`,
      type: 'number',
      defaultDirection: 'desc',
      hasTotal: true,
      width: '120px',
    },
    IDEAL_ALT_QTY: {
      textKey: 'idealAltQtyFormatted',
      valueKey: 'idealAltQty',
      id: measure.IDEAL_ALT_QTY,
      text: `${i18n.global.t('idealqty')} (${i18n.global.t('Alternative unit').toLowerCase()})`,
      type: 'number',
      defaultDirection: 'desc',
      hasTotal: true,
      width: '120px',
    },
    PERFORMANCE_LOSS_QTY: {
      textKey: 'performanceLossQtyFormatted',
      valueKey: 'performanceLossQty',
      id: calcMeasure.PERFORMANCE_LOSS_QTY,
      text: `${i18n.global.t('Loss')} – ${i18n.global.t('performance')} (${i18n.global.t('Primary unit').toLowerCase()})`,
      type: 'number',
      defaultDirection: 'desc',
      hasTotal: true,
      width: '120px',
    },
    PERFORMANCE_LOSS_ALT_QTY: {
      textKey: 'performanceLossAltQtyFormatted',
      valueKey: 'performanceLossAltQty',
      id: calcMeasure.PERFORMANCE_LOSS_ALT_QTY,
      text: `${i18n.global.t('Loss')} – ${i18n.global.t('performance')} (${i18n.global.t('Alternative unit').toLowerCase()})`,
      type: 'number',
      defaultDirection: 'desc',
      hasTotal: true,
      width: '120px',
    },
    AVAILABILITY_LOSS_QTY: {
      textKey: 'availabilityLossQtyFormatted',
      valueKey: 'availabilityLossQty',
      id: calcMeasure.AVAILABILITY_LOSS_QTY,
      text: `${i18n.global.t('Loss')} – ${i18n.global.t('availability')} (${i18n.global.t('Primary unit').toLowerCase()})`,
      type: 'number',
      defaultDirection: 'desc',
      hasTotal: true,
      width: '120px',
    },
    AVAILABILITY_LOSS_ALT_QTY: {
      textKey: 'availabilityLossAltQtyFormatted',
      valueKey: 'availabilityLossAltQty',
      id: calcMeasure.AVAILABILITY_LOSS_ALT_QTY,
      text: `${i18n.global.t('Loss')} – ${i18n.global.t('availability')} (${i18n.global.t('Alternative unit').toLowerCase()})`,
      type: 'number',
      defaultDirection: 'desc',
      hasTotal: true,
      width: '120px',
    },

  };
}
