import i18n from '@/services/i18n';
import measure from '@/stores/reportsConfig/constants/measure';
import formatDuration from '@/helpers/time/formatDuration';

export default function getTimeUsageColumns(options) {
  return {
    GOOD_PRODUCTION: {
      textKey: 'goodProduction',
      secondaryTextKey: 'goodDurPctFormatted',
      secondaryTextTooltip: `${i18n.global.t('plannedTime')} / ${i18n.global.t('Shift time')}`,
      valueKey: 'goodProduction',
      id: measure.GOOD_PRODUCTION,
      text: i18n.global.t('goodproduction'),
      type: 'number',
      defaultDirection: 'desc',
      hasTotal: true,
      isDurationValue: true,
      formatFn: (val) => formatDuration(val, options.durFormatType, { keepDecimalPlaces: true }),
      width: '120px',
    },
    SLOW_PRODUCTION: {
      textKey: 'slowProduction',
      secondaryTextKey: 'slowPctFormatted',
      secondaryTextTooltip: `${i18n.global.t('plannedTime')} / ${i18n.global.t('Shift time')}`,
      valueKey: 'slowProduction',
      id: measure.SLOW_PRODUCTION,
      text: i18n.global.t('Speed loss'),
      type: 'number',
      defaultDirection: 'desc',
      hasTotal: true,
      isDurationValue: true,
      formatFn: (val) => formatDuration(val, options.durFormatType, { keepDecimalPlaces: true }),
      width: '120px',
    },
    PLANNED_STOP_INCLUDED_IN_OEE: {
      textKey: 'plannedStopIncludedInOEE',
      secondaryTextKey: 'plannedIncludedInOEEPctFormatted',
      secondaryTextTooltip: `${i18n.global.t('plannedTime')} / ${i18n.global.t('Shift time')}`,
      valueKey: 'plannedStopIncludedInOEE',
      id: measure.PLANNED_STOP_INCLUDED_IN_OEE,
      text: `${i18n.global.t('Planned stops')} (${i18n.global.t('incl. in OEE')})`,
      type: 'number',
      defaultDirection: 'desc',
      hasTotal: true,
      isDurationValue: true,
      formatFn: (val) => formatDuration(val, options.durFormatType, { keepDecimalPlaces: true }),
      width: '120px',
    },
    PLANNED_STOP_NOT_INCLUDED_IN_OEE: {
      textKey: 'plannedStopNotIncludedInOEE',
      secondaryTextKey: 'plannedNotIncludedInOEEPctFormatted',
      secondaryTextTooltip: i18n.global.t('Shift time'),
      valueKey: 'plannedStopNotIncludedInOEE',
      id: measure.PLANNED_STOP_NOT_INCLUDED_IN_OEE,
      text: `${i18n.global.t('Planned stops')} (${i18n.global.t('excl. from OEE')})`,
      type: 'number',
      defaultDirection: 'desc',
      hasTotal: true,
      isDurationValue: true,
      formatFn: (val) => formatDuration(val, options.durFormatType, { keepDecimalPlaces: true }),
      width: '120px',
    },
    UNPLANNED_STOP: {
      textKey: 'unplannedStop',
      secondaryTextKey: 'unplannedPctFormatted',
      secondaryTextTooltip: `${i18n.global.t('plannedTime')} / ${i18n.global.t('Shift time')}`,
      valueKey: 'unplannedStop',
      id: measure.UNPLANNED_STOP,
      text: i18n.global.t('Unplanned stops'),
      type: 'number',
      defaultDirection: 'desc',
      hasTotal: true,
      isDurationValue: true,
      formatFn: (val) => formatDuration(val, options.durFormatType, { keepDecimalPlaces: true }),
      width: '170px',
    },
    UNCOMMENTED_STOP: {
      textKey: 'uncommentedStop',
      secondaryTextKey: 'uncommentedPctFormatted',
      secondaryTextTooltip: `${i18n.global.t('plannedTime')} / ${i18n.global.t('Shift time')}`,
      valueKey: 'uncommentedStop',
      id: measure.UNCOMMENTED_STOP,
      text: i18n.global.t('Uncommented stop'),
      type: 'number',
      defaultDirection: 'desc',
      hasTotal: true,
      isDurationValue: true,
      formatFn: (val) => formatDuration(val, options.durFormatType, { keepDecimalPlaces: true }),
      width: '150px',
    },

  };
}
